// src/app/features/tasks/ui/group-item/group-item.component.ts
import { ChangeDetectionStrategy, Component, computed, inject, input, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CdkDrag, CdkDragDrop, CdkDragHandle, CdkDropList } from '@angular/cdk/drag-drop';
import { LucideAngularModule } from 'lucide-angular';
import { AutofocusDirective } from '@shared/ui/autofocus/autofocus.directive';
import { ButtonDirective } from '@shared/ui/button/button.directive';
import { InputDirective } from '@shared/ui/input/input.directive';
import { CardComponent, CardContentComponent } from '@shared/ui/card/card.component';
import { cn } from '@shared/utils/cn';
import { isVisibleToday } from '@features/tasks/data-access/tasks.tree';
import { TaskStateService } from '@features/tasks/data-access/tasks.state';
import type { Group, Task } from '@features/tasks/data-access/tasks.types';
import { TaskItemComponent } from '@features/tasks/ui/task-item/task-item.component';

@Component({
  selector: 'app-group-item',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    FormsModule,
    CdkDrag,
    CdkDragHandle,
    CdkDropList,
    LucideAngularModule,
    AutofocusDirective,
    ButtonDirective,
    InputDirective,
    CardComponent,
    CardContentComponent,
    TaskItemComponent,
  ],
  templateUrl: './group-item.component.html',
  host: {
    class: 'block',
  },
})
export class GroupItemComponent {
  private readonly state = inject(TaskStateService);

  readonly group = input.required<Group>();

  protected readonly hovered = signal(false);
  protected readonly editing = signal(false);
  protected readonly editedName = signal('');
  protected readonly newTaskName = signal('');

  protected readonly visibleTasks = computed(() =>
    this.group()
      .tasks.filter(isVisibleToday)
      .slice()
      .sort((a, b) => a.order - b.order),
  );

  protected readonly visibleTaskCount = computed(() => this.visibleTasks().length);

  protected readonly deleteBtnClass = computed(() =>
    cn(
      'h-8 w-8 text-muted-foreground hover:text-destructive hover:bg-destructive/10 transition-opacity',
      this.hovered() ? 'opacity-100' : 'opacity-0',
    ),
  );

  protected toggleOpen(): void {
    this.state.toggleGroupOpen(this.group().id, !this.group().isOpen);
  }

  protected delete(): void {
    this.state.deleteGroup(this.group().id);
  }

  protected startEditing(): void {
    this.editedName.set(this.group().name);
    this.editing.set(true);
  }

  protected saveName(): void {
    if (!this.editing()) return;
    const trimmed = this.editedName().trim();
    if (trimmed && trimmed !== this.group().name) {
      this.state.renameGroup(this.group().id, trimmed);
    }
    this.editing.set(false);
  }

  protected onEditKey(event: KeyboardEvent): void {
    if (event.key === 'Enter') this.saveName();
    if (event.key === 'Escape') {
      this.editedName.set(this.group().name);
      this.editing.set(false);
    }
  }

  protected addTask(event: Event): void {
    event.preventDefault();
    const name = this.newTaskName().trim();
    if (!name) return;
    this.state.addRootTask(this.group().id, name);
    this.newTaskName.set('');
  }

  protected onTaskDrop(event: CdkDragDrop<Task[]>): void {
    if (event.previousIndex === event.currentIndex) return;
    this.state.reorderTasks(this.group().id, null, event.previousIndex, event.currentIndex);
  }
}

<app-card
  class="mb-4 border-2 overflow-hidden shadow-sm hover:shadow-md transition-all"
  (mouseenter)="hovered.set(true)"
  (mouseleave)="hovered.set(false)"
>
  <div class="bg-gradient-to-r from-primary/5 to-primary/10 border-b border-border">
    <div class="flex items-center gap-3 px-4 py-3">
      <span
        cdkDragHandle
        class="cursor-grab active:cursor-grabbing text-muted-foreground/50 hover:text-muted-foreground transition-colors"
      >
        <lucide-icon name="grip-vertical" class="h-5 w-5" />
      </span>

      <button
        appButton
        variant="ghost"
        size="icon"
        btnClass="h-8 w-8 hover:bg-primary/10"
        (click)="toggleOpen()"
        [attr.aria-expanded]="group().isOpen"
        type="button"
      >
        @if (group().isOpen) {
          <lucide-icon name="folder-open" class="h-5 w-5 text-primary" />
        } @else {
          <lucide-icon name="folder" class="h-5 w-5 text-primary" />
        }
      </button>

      @if (editing()) {
        <input
          appInput
          appAutofocus
          [ngModel]="editedName()"
          (ngModelChange)="editedName.set($event)"
          name="groupName"
          (blur)="saveName()"
          (keydown)="onEditKey($event)"
          class="h-8 font-semibold text-base flex-1"
        />
      } @else {
        <h3
          class="font-semibold text-base flex-1 cursor-pointer hover:text-primary transition-colors"
          (dblclick)="startEditing()"
        >
          {{ group().name }}
        </h3>
      }

      <div class="flex items-center gap-2">
        @if (visibleTaskCount() > 0) {
          <span class="text-xs font-medium px-2 py-1 rounded-full bg-primary/20 text-primary">
            {{ visibleTaskCount() }}
            {{ visibleTaskCount() === 1 ? 'task' : 'tasks' }}
          </span>
        }

        <button
          appButton
          variant="ghost"
          size="icon"
          [btnClass]="deleteBtnClass()"
          (click)="delete()"
          title="Delete group"
          type="button"
        >
          <lucide-icon name="trash-2" class="h-4 w-4" />
        </button>
      </div>
    </div>
  </div>

  @if (group().isOpen) {
    <app-card-content>
      <form (submit)="addTask($event)" class="flex gap-2 mb-4">
        <input
          appInput
          [ngModel]="newTaskName()"
          (ngModelChange)="newTaskName.set($event)"
          name="taskName"
          placeholder="Add a new task..."
          class="h-10 border-dashed"
        />
        <button appButton btnClass="h-10 px-5" type="submit">
          <lucide-icon name="plus" class="h-4 w-4" />
          Add
        </button>
      </form>

      @if (visibleTasks().length > 0) {
        <div cdkDropList (cdkDropListDropped)="onTaskDrop($event)" class="space-y-1">
          @for (task of visibleTasks(); track task.id) {
            <div cdkDrag>
              <app-task-item [task]="task" [groupId]="group().id" />
            </div>
          }
        </div>
      } @else {
        <div class="text-center py-8 text-muted-foreground text-sm">
          No tasks yet. Add one above to get started.
        </div>
      }
    </app-card-content>
  }
</app-card>

// src/features/workspace/GroupItem.tsx
import { For, Show, createSignal } from 'solid-js'
import { Folder, FolderOpen, GripVertical, Plus, Trash2 } from 'lucide-solid'
import {
  createSortable,
  SortableProvider,
  maybeTransformStyle,
  useDragDropContext,
} from '@thisbeyond/solid-dnd'
import { cn } from '~/lib/classnames'
import { useWorkspace } from '~/state/workspaceContext'
import { isVisibleToday } from '~/features/tasks/tree'
import type { Group } from '~/features/groups/types'
import type { Task } from '~/features/tasks/types'
import TaskItem from './TaskItem'
import { GROUPS_LIST_KEY, type ItemDragData } from './dnd'

/**
 * One group card. The whole card is a sortable in the workspace's groups list:
 * it drags under the cursor while sibling groups shift to open a slot. The
 * expanded body renders the group's root tasks as their own sortable list.
 */

interface Props {
  group: Group
}

export default function GroupItem(props: Props) {
  const ws = useWorkspace()
  const sortable = createSortable(props.group.id, {
    kind: 'item',
    itemKind: 'group',
    listKey: GROUPS_LIST_KEY,
  } satisfies ItemDragData)
  const dnd = useDragDropContext()
  const isDragging = (): boolean => !!dnd?.[0].active.draggable

  const [hovered, setHovered] = createSignal(false)
  const [editing, setEditing] = createSignal(false)
  const [editedName, setEditedName] = createSignal('')
  const [newTaskName, setNewTaskName] = createSignal('')

  const visibleTasks = (): Task[] =>
    ws.tasks
      .tasksFor(props.group.id)
      .filter(isVisibleToday)
      .slice()
      .sort((a, b) => a.order - b.order)

  const visibleTaskCount = (): number => visibleTasks().length

  const startEditing = (): void => {
    setEditedName(props.group.name)
    setEditing(true)
  }

  const saveName = (): void => {
    if (!editing()) return
    const trimmed = editedName().trim()
    if (trimmed && trimmed !== props.group.name) {
      void ws.groups.rename(props.group.id, trimmed)
    }
    setEditing(false)
  }

  const onEditKey = (event: KeyboardEvent): void => {
    if (event.key === 'Enter') saveName()
    if (event.key === 'Escape') {
      setEditedName(props.group.name)
      setEditing(false)
    }
  }

  const submitTask = (event: Event): void => {
    event.preventDefault()
    const trimmed = newTaskName().trim()
    if (!trimmed) return
    void ws.tasks.add(props.group.id, trimmed)
    setNewTaskName('')
  }

  return (
    <section
      ref={sortable.ref}
      // solid-dnd writes the live drag/sort offset as an inline transform; the
      // dragged card follows the cursor at 25% opacity while siblings slide.
      // `transition-transform` smooths the SIBLING shift only — never the active
      // card, or its per-frame pointer transform would ease behind the cursor
      // and feel laggy.
      style={maybeTransformStyle(sortable.transform)}
      class={cn(
        'rounded-lg border-2 border-border bg-secondary-background shadow-brutal overflow-hidden',
        isDragging() && !sortable.isActiveDraggable && 'transition-transform',
        sortable.isActiveDraggable && 'opacity-25',
      )}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      data-testid={`group-item-${props.group.id}`}
    >
      <header class="flex items-center gap-2 px-4 py-3">
        <span
          {...sortable.dragActivators}
          class={cn(
            'inline-flex cursor-grab active:cursor-grabbing text-subtle-foreground hover:text-foreground transition-opacity',
            hovered() ? 'opacity-100' : 'opacity-0',
          )}
          // Decorative — the drag affordance is mouse/touch only. Keyboard
          // users can't activate it, so labeling it for screen readers would
          // advertise an action they can't perform.
          aria-hidden="true"
        >
          <GripVertical size={20} />
        </span>

        <button
          type="button"
          class="tap-44 inline-flex h-8 w-8 items-center justify-center rounded-md text-foreground hover:bg-foreground/5 transition-colors cursor-pointer"
          onClick={() => void ws.groups.toggleOpen(props.group.id, !props.group.isOpen)}
          aria-expanded={props.group.isOpen}
          aria-label={props.group.isOpen ? 'Collapse group' : 'Expand group'}
        >
          <Show when={props.group.isOpen} fallback={<Folder size={20} />}>
            <FolderOpen size={20} />
          </Show>
        </button>

        <Show
          when={editing()}
          fallback={
            <h2
              class="flex-1 cursor-text select-none truncate text-xl font-bold tracking-tight"
              onDblClick={startEditing}
              title="Double-click to rename"
            >
              {props.group.name}
            </h2>
          }
        >
          <input
            ref={(el) => {
              setTimeout(() => {
                el?.focus()
                el?.select()
              }, 0)
            }}
            type="text"
            value={editedName()}
            onInput={(e) => setEditedName(e.currentTarget.value)}
            onBlur={saveName}
            onKeyDown={onEditKey}
            class="flex h-9 w-full flex-1 rounded-md border-2 border-border bg-secondary-background px-3 py-2 text-xl font-bold text-foreground shadow-brutal-sm focus-visible:shadow-brutal transition-shadow"
            autocomplete="off"
            autocorrect="off"
            autocapitalize="off"
            spellcheck={false}
            aria-label="Rename group"
          />
        </Show>

        <Show when={visibleTaskCount() > 0}>
          <span
            class="readout text-sm font-semibold text-muted-foreground"
            aria-label={`${visibleTaskCount()} ${visibleTaskCount() === 1 ? 'task' : 'tasks'}`}
          >
            {visibleTaskCount()}
          </span>
        </Show>

        <button
          type="button"
          class={cn(
            'tap-44 inline-flex h-8 w-8 items-center justify-center rounded-md bg-destructive text-destructive-foreground border-2 border-border shadow-brutal-sm brutal-press transition-opacity cursor-pointer',
            hovered() ? 'opacity-100' : 'opacity-0',
          )}
          onClick={() => void ws.groups.delete(props.group.id)}
          title="Delete group"
          aria-label="Delete group"
        >
          <Trash2 size={16} />
        </button>
      </header>

      <Show when={props.group.isOpen}>
        <div class="border-t border-foreground/15">
          <Show
            when={visibleTasks().length > 0}
            fallback={
              <p class="py-5 text-center text-sm font-medium text-subtle-foreground">
                No tasks yet.
              </p>
            }
          >
            <div class="py-1.5 space-y-1">
              <SortableProvider ids={visibleTasks().map((t) => t.id)}>
                <For each={visibleTasks()}>{(task) => (
                  <TaskItem task={task} groupId={props.group.id} parentId={null} />
                )}</For>
              </SortableProvider>
            </div>
          </Show>

          <form
            onSubmit={submitTask}
            class="flex gap-2 border-t border-foreground/10 bg-foreground/[0.02] px-3 py-2.5"
          >
            <input
              type="text"
              value={newTaskName()}
              onInput={(e) => setNewTaskName(e.currentTarget.value)}
              placeholder="Add a task…"
              autocomplete="off"
              autocorrect="off"
              autocapitalize="off"
              spellcheck={false}
              aria-label={`Add a task to ${props.group.name}`}
              class="flex h-9 w-full flex-1 rounded-md border-2 border-border bg-secondary-background px-3 py-2 text-sm font-medium text-foreground placeholder:text-subtle-foreground shadow-brutal-sm focus-visible:shadow-brutal transition-shadow"
            />
            <button
              type="submit"
              disabled={!newTaskName().trim()}
              class="inline-flex h-9 items-center justify-center gap-2 px-4 rounded-md bg-secondary-background text-foreground border-2 border-border shadow-brutal-sm brutal-press font-bold text-sm cursor-pointer disabled:opacity-50 disabled:pointer-events-none"
            >
              <Plus size={16} />
              Add
            </button>
          </form>
        </div>
      </Show>
    </section>
  )
}
