// src/components/Dropdown.tsx
import { createSignal, For, onCleanup, onMount, Show } from 'solid-js'
import { ChevronDown, Check } from 'lucide-solid'
import { cn } from '~/lib/classnames'

/**
 * Anchored dropdown ported from client-web-old/.../dropdown.component.{ts,html}.
 * Same trigger styling, same options list, same listbox/option ARIA roles.
 * Implementation difference: instead of Angular CDK overlay we use plain
 * absolute positioning relative to the trigger (cheaper on low-end devices)
 * with a `pointerdown` outside-click listener and ESC to dismiss.
 */

export interface DropdownOption {
  value: string
  label: string
}

interface DropdownProps {
  options: DropdownOption[]
  value: string
  placeholder?: string
  onValueChange: (value: string) => void
  class?: string
}

export default function Dropdown(props: DropdownProps) {
  const [open, setOpen] = createSignal(false)
  let triggerRef: HTMLButtonElement | undefined
  let rootRef: HTMLDivElement | undefined

  const selectedLabel = (): string => {
    const current = props.options.find((o) => o.value === props.value)
    return current?.label ?? (props.placeholder ?? 'Select…')
  }

  const select = (value: string): void => {
    props.onValueChange(value)
    setOpen(false)
    triggerRef?.focus()
  }

  const handleDocPointerDown = (e: PointerEvent): void => {
    if (!open()) return
    if (rootRef && !rootRef.contains(e.target as Node)) {
      setOpen(false)
    }
  }

  const handleKeyDown = (e: KeyboardEvent): void => {
    if (e.key === 'Escape' && open()) {
      e.stopPropagation()
      setOpen(false)
      triggerRef?.focus()
    }
  }

  onMount(() => {
    document.addEventListener('pointerdown', handleDocPointerDown)
    document.addEventListener('keydown', handleKeyDown)
  })
  onCleanup(() => {
    document.removeEventListener('pointerdown', handleDocPointerDown)
    document.removeEventListener('keydown', handleKeyDown)
  })

  return (
    <div ref={rootRef} class={cn('relative', props.class)}>
      <button
        ref={triggerRef}
        type="button"
        onClick={() => setOpen(!open())}
        aria-expanded={open()}
        aria-haspopup="listbox"
        class="flex h-9 w-full items-center justify-between gap-2 rounded-md border-2 border-border bg-secondary-background px-3 text-sm font-medium text-foreground shadow-brutal-sm cursor-pointer transition-shadow hover:shadow-brutal"
      >
        <span class="truncate text-left">{selectedLabel()}</span>
        <ChevronDown
          size={16}
          class={cn('shrink-0 transition-transform', open() && 'rotate-180')}
        />
      </button>

      <Show when={open()}>
        <div
          role="listbox"
          class="absolute left-0 right-0 top-[calc(100%+6px)] z-10 max-h-64 overflow-y-auto rounded-md border-2 border-border bg-background shadow-brutal"
        >
          <For each={props.options}>{(option) => (
            <button
              type="button"
              role="option"
              aria-selected={props.value === option.value}
              onClick={() => select(option.value)}
              class={cn(
                'flex w-full items-center justify-between gap-2 px-3 py-2 text-left text-sm font-semibold tracking-tight hover:bg-secondary-background transition-colors',
                props.value === option.value && 'bg-primary-soft',
              )}
            >
              <span class="truncate">{option.label}</span>
              <Show when={props.value === option.value}>
                <Check size={16} class="shrink-0" />
              </Show>
            </button>
          )}</For>
        </div>
      </Show>
    </div>
  )
}

// src/app/shared/ui/dropdown/dropdown.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  computed,
  input,
  output,
  signal,
  viewChild,
} from '@angular/core';
import { OverlayModule, type ConnectedPosition } from '@angular/cdk/overlay';
import { LucideAngularModule } from 'lucide-angular';

export interface DropdownOption {
  value: string;
  label: string;
}

@Component({
  selector: 'app-dropdown',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [OverlayModule, LucideAngularModule],
  templateUrl: './dropdown.component.html',
})
export class DropdownComponent {
  readonly options = input.required<DropdownOption[]>();
  readonly value = input<string>('');
  readonly placeholder = input<string>('Select…');

  readonly valueChange = output<string>();

  private readonly triggerEl = viewChild<ElementRef<HTMLButtonElement>>('triggerEl');

  protected readonly open = signal(false);
  protected readonly triggerWidth = signal(0);

  protected readonly selectedLabel = computed<string>(() => {
    const current = this.options().find((o) => o.value === this.value());
    return current?.label ?? this.placeholder();
  });

  protected readonly positions: ConnectedPosition[] = [
    {
      originX: 'start',
      originY: 'bottom',
      overlayX: 'start',
      overlayY: 'top',
      offsetY: 6,
    },
    {
      originX: 'start',
      originY: 'top',
      overlayX: 'start',
      overlayY: 'bottom',
      offsetY: -6,
    },
  ];

  protected toggle(): void {
    if (!this.open()) {
      this.triggerWidth.set(this.triggerEl()?.nativeElement.offsetWidth ?? 0);
    }
    this.open.update((v) => !v);
  }

  protected select(value: string): void {
    this.valueChange.emit(value);
    this.open.set(false);
    this.triggerEl()?.nativeElement.focus();
  }

  protected onMenuKeydown(event: KeyboardEvent): void {
    if (event.key === 'Escape') {
      event.stopPropagation();
      this.open.set(false);
      this.triggerEl()?.nativeElement.focus();
    }
  }
}

<button
  #triggerEl
  cdkOverlayOrigin
  #origin="cdkOverlayOrigin"
  type="button"
  (click)="toggle()"
  [attr.aria-expanded]="open()"
  class="flex h-9 w-full items-center justify-between gap-2 rounded-md border-2 border-border bg-secondary-background px-3 text-sm font-medium text-foreground shadow-brutal-sm cursor-pointer transition-shadow hover:shadow-brutal"
>
  <span class="truncate text-left">{{ selectedLabel() }}</span>
  <lucide-icon
    name="chevron-down"
    class="h-4 w-4 shrink-0 transition-transform"
    [class.rotate-180]="open()"
  />
</button>

<ng-template
  cdkConnectedOverlay
  [cdkConnectedOverlayOrigin]="origin"
  [cdkConnectedOverlayOpen]="open()"
  [cdkConnectedOverlayPositions]="positions"
  [cdkConnectedOverlayHasBackdrop]="true"
  cdkConnectedOverlayBackdropClass="cdk-overlay-transparent-backdrop"
  (backdropClick)="open.set(false)"
  (detach)="open.set(false)"
  (overlayKeydown)="onMenuKeydown($event)"
>
  <div
    [style.width.px]="triggerWidth()"
    class="rounded-md border-2 border-border bg-background shadow-brutal overflow-hidden max-h-64 overflow-y-auto"
    role="listbox"
  >
    @for (option of options(); track option.value) {
      <button
        type="button"
        role="option"
        [attr.aria-selected]="value() === option.value"
        (click)="select(option.value)"
        class="flex w-full items-center justify-between gap-2 px-3 py-2 text-left text-sm font-semibold tracking-tight hover:bg-secondary-background transition-colors"
        [class.bg-primary-soft]="value() === option.value"
      >
        <span class="truncate">{{ option.label }}</span>
        @if (value() === option.value) {
          <lucide-icon name="check" class="h-4 w-4 shrink-0" />
        }
      </button>
    }
  </div>
</ng-template>
