// src/features/alarms/AlarmFiringModal.tsx
import { Show, createEffect } from 'solid-js'
import { BellRing, Check, X } from 'lucide-solid'
import Button from '~/components/Button'
import { useWorkspace } from '~/state/workspaceContext'
import { formatAlarmTime } from './lib/alarmFormat'

/**
 * Global modal that appears whenever the alarms scheduler reports a firing
 * alarm. Done completes the associated task and dismisses; Dismiss only
 * dismisses. Backdrop click does not close (this is an attention-required UX
 * — the user has to commit one way or the other).
 */

export default function AlarmFiringModal() {
  const ws = useWorkspace()
  let dialogRef: HTMLDialogElement | undefined

  createEffect(() => {
    if (!dialogRef) return
    const open = ws.alarmsScheduler.firing() !== null
    if (open && !dialogRef.open) dialogRef.showModal()
    else if (!open && dialogRef.open) dialogRef.close()
  })

  const firingTime = (): string => {
    const iso = ws.alarmsScheduler.firing()?.task.alarm?.firesAt
    if (!iso) return ''
    return formatAlarmTime(iso).replace(/^(Today|Tomorrow) /, '')
  }

  const onDone = (): void => {
    const f = ws.alarmsScheduler.firing()
    if (!f) return
    void ws.tasks.toggleCompletion(f.groupId, f.task.id)
    ws.alarmsScheduler.dismiss()
  }

  const onDismiss = (): void => {
    ws.alarmsScheduler.dismiss()
  }

  return (
    <dialog
      ref={dialogRef}
      aria-label="Alarm firing"
      // m-auto: restore native <dialog> centering (Tailwind v4 preflight wipes
      // out `margin: auto` from the user-agent dialog style).
      class="m-auto rounded-md border-2 border-border bg-background shadow-brutal p-0 backdrop:bg-foreground/80 max-w-md max-h-[calc(100vh-2rem)]"
    >
      <Show when={ws.alarmsScheduler.firing()}>
        {(firing) => (
          <div class="w-full max-w-md p-6 space-y-5">
            <div class="flex items-center gap-4">
              <span class="inline-flex h-14 w-14 shrink-0 items-center justify-center rounded-full bg-warning text-warning-foreground border-2 border-border shadow-brutal">
                <BellRing size={28} class="motion-safe:animate-pulse" />
              </span>
              <div class="flex-1 min-w-0">
                <p class="text-[0.6875rem] font-bold uppercase tracking-[0.1em] text-subtle-foreground">
                  Alarm fired
                </p>
                <Show when={firingTime()}>
                  <p class="readout text-2xl font-bold leading-none mt-1">
                    {firingTime()}
                  </p>
                </Show>
              </div>
            </div>

            <h2 class="text-xl font-bold tracking-tight break-words leading-snug">
              {firing().task.name}
            </h2>

            <div class="flex gap-2">
              <Button variant="success" size="lg" btnClass="flex-1" onClick={onDone}>
                <Check size={20} />
                Done
              </Button>
              <Button variant="neutral" size="lg" btnClass="flex-1" onClick={onDismiss}>
                <X size={20} />
                Dismiss
              </Button>
            </div>
          </div>
        )}
      </Show>
    </dialog>
  )
}

// src/app/features/alarms/feature/alarm-firing-modal/alarm-firing-modal.component.ts
import { ChangeDetectionStrategy, Component, computed, inject } from '@angular/core';
import { LucideAngularModule } from 'lucide-angular';
import { ButtonDirective } from '@shared/ui/button/button.directive';
import { formatAlarmTime } from '@features/alarms/data-access/alarm-format';
import { AlarmsScheduler } from '@features/alarms/data-access/alarms.scheduler';
import { WorkspaceState } from '@features/workspace/data-access/workspace.state';

@Component({
  selector: 'app-alarm-firing-modal',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [LucideAngularModule, ButtonDirective],
  templateUrl: './alarm-firing-modal.component.html',
})
export class AlarmFiringModalComponent {
  private readonly scheduler = inject(AlarmsScheduler);
  private readonly workspace = inject(WorkspaceState);

  protected readonly firing = this.scheduler.firing;

  protected readonly firingTime = computed(() => {
    const iso = this.firing()?.task.alarm?.firesAt;
    if (!iso) return '';
    return formatAlarmTime(iso).replace(/^(Today|Tomorrow) /, '');
  });

  protected onDone(): void {
    const f = this.firing();
    if (!f) return;
    this.workspace.toggleTaskCompletion(f.groupId, f.task.id);
    this.scheduler.dismiss();
  }

  protected onDismiss(): void {
    this.scheduler.dismiss();
  }
}

@if (firing(); as f) {
  <div
    class="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4"
    role="dialog"
    aria-modal="true"
    aria-labelledby="alarm-firing-title"
  >
    <div
      class="w-full max-w-md rounded-md border-2 border-border bg-background shadow-brutal p-6 space-y-5"
    >
      <div class="flex items-center gap-4">
        <span
          class="inline-flex h-14 w-14 shrink-0 items-center justify-center rounded-full bg-warning text-warning-foreground border-2 border-border shadow-brutal"
        >
          <lucide-icon name="bell-ring" class="h-7 w-7 animate-pulse" />
        </span>
        <div class="flex-1 min-w-0">
          <p class="text-[0.6875rem] font-bold uppercase tracking-[0.1em] text-subtle-foreground">
            Alarm fired
          </p>
          @if (firingTime()) {
            <p class="readout text-2xl font-bold leading-none mt-1">{{ firingTime() }}</p>
          }
        </div>
      </div>

      <h2 id="alarm-firing-title" class="text-xl font-bold tracking-tight break-words leading-snug">
        {{ f.task.name }}
      </h2>

      <div class="flex gap-2">
        <button
          appButton
          variant="success"
          size="lg"
          btnClass="flex-1"
          (click)="onDone()"
          type="button"
        >
          <lucide-icon name="check" class="h-5 w-5" />
          Done
        </button>
        <button
          appButton
          variant="neutral"
          size="lg"
          btnClass="flex-1"
          (click)="onDismiss()"
          type="button"
        >
          <lucide-icon name="x" class="h-5 w-5" />
          Dismiss
        </button>
      </div>
    </div>
  </div>
}
