// src/features/sounds/SettingsPage.tsx
import { For, Show, createSignal, onCleanup } from 'solid-js'
import { A } from '@solidjs/router'
import { Music, Upload } from 'lucide-solid'
import Button, { buttonClasses } from '~/components/Button'
import { Card } from '~/components/Card'
import { useWorkspace } from '~/state/workspaceContext'
import SoundListItem from './SoundListItem'

/**
 * Sound library settings page. Lists every uploaded sound, lets the user
 * upload more (audio/* multi-select; non-audio silently skipped), set/clear
 * the default, preview-play, and delete. Preview uses a plain HTMLAudioElement
 * — T12 brings the richer Web Audio playback layer used by alarms and timers.
 */

export default function SettingsPage() {
  const ws = useWorkspace()

  const [playingId, setPlayingId] = createSignal<string | null>(null)
  const [busy, setBusy] = createSignal(false)
  let fileInputRef: HTMLInputElement | undefined
  let currentAudio: HTMLAudioElement | null = null
  let currentObjectUrl: string | null = null

  const stopPreview = (): void => {
    if (currentAudio) {
      currentAudio.pause()
      currentAudio.src = ''
    }
    if (currentObjectUrl) {
      URL.revokeObjectURL(currentObjectUrl)
    }
    currentAudio = null
    currentObjectUrl = null
    setPlayingId(null)
  }

  onCleanup(stopPreview)

  const togglePreview = async (soundId: string): Promise<void> => {
    if (playingId() === soundId) {
      stopPreview()
      return
    }
    stopPreview()
    const blob = await ws.sounds.getBlob(soundId)
    if (!blob) return
    const url = URL.createObjectURL(blob)
    const audio = new Audio(url)
    audio.loop = true
    audio.addEventListener('ended', stopPreview)
    try {
      await audio.play()
      currentAudio = audio
      currentObjectUrl = url
      setPlayingId(soundId)
    } catch {
      URL.revokeObjectURL(url)
    }
  }

  const onUploadClick = (): void => {
    fileInputRef?.click()
  }

  const onFileChange = async (event: Event): Promise<void> => {
    const target = event.target as HTMLInputElement
    const files = Array.from(target.files ?? [])
    target.value = ''
    if (files.length === 0 || busy()) return
    setBusy(true)
    try {
      for (const file of files) {
        if (!file.type.startsWith('audio/')) continue
        await ws.sounds.addSound(file)
      }
    } finally {
      setBusy(false)
    }
  }

  const onSetDefault = (soundId: string): void => {
    const next = ws.sounds.state.defaultSoundId === soundId ? null : soundId
    void ws.sounds.setDefault(next)
  }

  const onDelete = (soundId: string): void => {
    if (playingId() === soundId) stopPreview()
    void ws.sounds.removeSound(soundId)
  }

  return (
    <main class="min-h-screen" aria-label="Sound library">
      <div class="max-w-2xl mx-auto px-5 py-10">
        <header class="mb-8 flex items-end justify-between gap-4">
          <div class="min-w-0 flex-1">
            <p class="text-[0.6875rem] font-bold uppercase tracking-[0.12em] text-subtle-foreground">
              Settings
            </p>
            <h1 class="mt-2 text-4xl sm:text-5xl font-black tracking-tighter text-foreground leading-none">
              Sound library
            </h1>
            <p class="mt-3 text-sm font-medium text-muted-foreground max-w-md">
              Upload sounds and pick a default. The default plays when a task
              has no sound of its own.
            </p>
          </div>
          <A href="/" class={buttonClasses({ variant: 'neutral' })}>
            Back
          </A>
        </header>

        <div class="mb-4 flex items-center justify-between gap-3">
          <span class="readout text-sm font-semibold text-muted-foreground">
            {ws.sounds.state.sounds.length}{' '}
            {ws.sounds.state.sounds.length === 1 ? 'sound' : 'sounds'}
          </span>
          <input
            ref={fileInputRef}
            type="file"
            accept="audio/*"
            multiple
            onChange={onFileChange}
            class="hidden"
            data-testid="sound-file-input"
          />
          <Button onClick={onUploadClick} disabled={busy()}>
            <Upload size={16} />
            Add sound
          </Button>
        </div>

        <Show when={ws.sounds.hasSounds()} fallback={<EmptyState />}>
          <Card>
            <ul class="divide-y-2 divide-border" role="list">
              <For each={ws.sounds.state.sounds}>{(sound) => (
                <SoundListItem
                  sound={sound}
                  isPlaying={playingId() === sound.id}
                  isDefault={ws.sounds.state.defaultSoundId === sound.id}
                  onPreviewToggle={() => void togglePreview(sound.id)}
                  onSetDefault={() => onSetDefault(sound.id)}
                  onDelete={() => onDelete(sound.id)}
                />
              )}</For>
            </ul>
          </Card>
        </Show>
      </div>
    </main>
  )
}

function EmptyState() {
  return (
    <div class="text-center rounded-lg border-2 border-dashed border-border/50 bg-secondary-background/40 py-14 px-6">
      <div class="mx-auto mb-5 inline-flex h-14 w-14 items-center justify-center rounded-md border-2 border-border bg-warning shadow-brutal">
        <Music size={28} class="text-warning-foreground" />
      </div>
      <h2 class="text-lg font-bold tracking-tight mb-1">No sounds yet.</h2>
      <p class="text-sm text-muted-foreground font-medium">
        Built-in beep plays until you add one.
      </p>
    </div>
  )
}

// src/app/features/settings/feature/settings-page/settings-page.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  computed,
  inject,
  signal,
  viewChild,
} from '@angular/core';
import { RouterLink } from '@angular/router';
import { LucideAngularModule } from 'lucide-angular';
import { ButtonDirective } from '@shared/ui/button/button.directive';
import { BytesPipe } from '@shared/ui/bytes/bytes.pipe';
import { CardComponent } from '@shared/ui/card/card.component';
import { PluralPipe } from '@shared/ui/plural/plural.pipe';
import { primeAudio, playSoundBlob, stopAlarm } from '@features/alarms/data-access/alarm-sound';
import { SoundsState } from '@features/sounds/data-access/sounds.state';

@Component({
  selector: 'app-settings-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterLink, LucideAngularModule, ButtonDirective, BytesPipe, CardComponent, PluralPipe],
  templateUrl: './settings-page.component.html',
})
export class SettingsPageComponent {
  protected readonly state = inject(SoundsState);

  private readonly fileInput = viewChild<ElementRef<HTMLInputElement>>('fileInput');

  protected readonly playingId = signal<string | null>(null);
  protected readonly busy = signal(false);

  protected readonly sounds = this.state.sounds;
  protected readonly defaultSoundId = this.state.defaultSoundId;

  protected readonly hasSounds = computed(() => this.sounds().length > 0);

  protected onUploadClick(): void {
    this.fileInput()?.nativeElement.click();
  }

  protected async onFileChange(event: Event): Promise<void> {
    const target = event.target as HTMLInputElement;
    const files = Array.from(target.files ?? []);
    target.value = '';
    if (files.length === 0 || this.busy()) return;
    this.busy.set(true);
    try {
      for (const file of files) {
        if (!file.type.startsWith('audio/')) continue;
        await this.state.addSound(file);
      }
    } finally {
      this.busy.set(false);
    }
  }

  protected async onPreview(soundId: string): Promise<void> {
    if (this.playingId() === soundId) {
      stopAlarm();
      this.playingId.set(null);
      return;
    }
    await primeAudio();
    const blob = await this.state.getBlob(soundId);
    if (!blob) return;
    playSoundBlob(blob, { loop: false });
    this.playingId.set(soundId);
  }

  protected async onSetDefault(soundId: string): Promise<void> {
    const next = this.defaultSoundId() === soundId ? null : soundId;
    await this.state.setDefault(next);
  }

  protected async onDelete(soundId: string): Promise<void> {
    if (this.playingId() === soundId) {
      stopAlarm();
      this.playingId.set(null);
    }
    await this.state.removeSound(soundId);
  }
}

<div class="min-h-screen">
  <div class="max-w-2xl mx-auto px-5 py-10">
    <header class="mb-8 flex items-end justify-between gap-4">
      <div class="min-w-0 flex-1">
        <p class="text-[0.6875rem] font-bold uppercase tracking-[0.12em] text-subtle-foreground">
          Settings
        </p>
        <h1
          class="mt-2 text-4xl sm:text-5xl font-black tracking-tighter text-foreground leading-none"
        >
          Sound library
        </h1>
        <p class="mt-3 text-sm font-medium text-muted-foreground max-w-md">
          Upload sounds and pick a default. The default plays when a task has no sound of its own.
        </p>
      </div>
      <a appButton variant="neutral" routerLink="/">Back</a>
    </header>

    <div class="mb-4 flex items-center justify-between gap-3">
      <span class="readout text-sm font-semibold text-muted-foreground">
        {{ sounds().length }} {{ sounds().length | plural: 'sound' : 'sounds' }}
      </span>
      <input
        #fileInput
        type="file"
        accept="audio/*"
        multiple
        (change)="onFileChange($event)"
        class="hidden"
      />
      <button appButton (click)="onUploadClick()" [disabled]="busy()" type="button">
        <lucide-icon name="upload" class="h-4 w-4" />
        Add sound
      </button>
    </div>

    @if (hasSounds()) {
      <app-card>
        <ul class="divide-y-2 divide-border" role="list">
          @for (sound of sounds(); track sound.id) {
            <li class="flex items-center gap-3 px-4 py-3">
              <button
                appButton
                variant="neutral"
                size="icon-sm"
                (click)="onPreview(sound.id)"
                [title]="playingId() === sound.id ? 'Stop preview' : 'Preview sound'"
                [attr.aria-label]="
                  playingId() === sound.id
                    ? 'Stop preview of ' + sound.name
                    : 'Preview ' + sound.name
                "
                type="button"
              >
                @if (playingId() === sound.id) {
                  <lucide-icon name="square" class="h-4 w-4" />
                } @else {
                  <lucide-icon name="play" class="h-4 w-4" />
                }
              </button>

              <div class="flex-1 min-w-0">
                <p class="font-bold tracking-tight truncate">{{ sound.name }}</p>
                <p class="readout text-xs font-medium text-muted-foreground">
                  {{ sound.sizeBytes | bytes }}
                </p>
              </div>

              @if (defaultSoundId() === sound.id) {
                <span
                  class="inline-flex items-center gap-1 rounded-md border-2 border-border bg-warning text-warning-foreground px-2 py-1 text-[0.6875rem] font-bold uppercase tracking-[0.08em] shadow-brutal-sm"
                >
                  <lucide-icon name="star" class="h-3.5 w-3.5" />
                  Default
                </span>
              }

              <button
                appButton
                [variant]="defaultSoundId() === sound.id ? 'warning' : 'ghost'"
                size="icon-sm"
                (click)="onSetDefault(sound.id)"
                [title]="defaultSoundId() === sound.id ? 'Unset as default' : 'Set as default'"
                [attr.aria-label]="
                  defaultSoundId() === sound.id
                    ? 'Unset ' + sound.name + ' as default'
                    : 'Set ' + sound.name + ' as default'
                "
                type="button"
              >
                <lucide-icon name="star" class="h-4 w-4" />
              </button>

              <button
                appButton
                variant="destructive"
                size="icon-sm"
                (click)="onDelete(sound.id)"
                title="Delete sound"
                [attr.aria-label]="'Delete ' + sound.name"
                type="button"
              >
                <lucide-icon name="trash-2" class="h-4 w-4" />
              </button>
            </li>
          }
        </ul>
      </app-card>
    } @else {
      <div
        class="text-center rounded-lg border-2 border-dashed border-border/50 bg-secondary-background/40 py-14 px-6"
      >
        <div
          class="mx-auto mb-5 inline-flex h-14 w-14 items-center justify-center rounded-md border-2 border-border bg-warning shadow-brutal"
        >
          <lucide-icon name="music" class="h-7 w-7 text-warning-foreground" />
        </div>
        <h3 class="text-lg font-bold tracking-tight mb-1">No sounds yet.</h3>
        <p class="text-sm text-muted-foreground font-medium">
          Built-in beep plays until you add one.
        </p>
      </div>
    }
  </div>
</div>
