// src/features/workspace/TaskItem.tsx
import { For, Show, createSignal, onCleanup, onMount } from 'solid-js'
import { Bell, Check, ChevronDown, GripVertical, Plus, Timer, Trash2 } from 'lucide-solid'
import { createDraggable } from '@thisbeyond/solid-dnd'
import { cn } from '~/lib/classnames'
import { todayIso } from '~/lib/date'
import { useWorkspace } from '~/state/workspaceContext'
import { isVisibleToday } from '~/features/tasks/tree'
import type { Task } from '~/features/tasks/types'
import type { AlarmSpec } from '~/features/alarms/types'
import type { TimerSet } from '~/features/timers/types'
import AlarmBadge from '~/features/alarms/AlarmBadge'
import AlarmPicker from '~/features/alarms/AlarmPicker'
import TimerBadge from '~/features/timers/TimerBadge'
import TimerEditor from '~/features/timers/TimerEditor'
import { sortedSets } from '~/features/timers/lib/timerFormat'
import Gap from './Gap'
import { rootTasksListKey, subtasksListKey, type ItemDragData } from './dnd'

/**
 * Recursive task row. The row itself is a draggable in its parent's list
 * (root tasks of the group, or subtasks of another task). Children render
 * inside their own gap-interleaved list using `subtasksListKey(...)`.
 */

interface Props {
  task: Task
  groupId: string
  parentId: string | null
}

export default function TaskItem(props: Props) {
  const ws = useWorkspace()

  const myListKey = (): string =>
    props.parentId === null
      ? rootTasksListKey(props.groupId)
      : subtasksListKey(props.groupId, props.parentId)

  const draggable = createDraggable(props.task.id, {
    kind: 'item',
    itemKind: 'task',
    listKey: myListKey() as ItemDragData['listKey'],
    groupId: props.groupId,
    parentId: props.parentId,
  } satisfies ItemDragData)

  const [hovered, setHovered] = createSignal(false)
  const [adding, setAdding] = createSignal(false)
  const [newSubtaskName, setNewSubtaskName] = createSignal('')
  const [pickingAlarm, setPickingAlarm] = createSignal(false)
  // `pickingTimer` is read from workspace context so it survives the
  // `TaskItem` remount triggered by `tasks.updateTimerSets` (which rebuilds
  // every `Task` reference). Local state here would be wiped on every
  // version add, slamming the modal shut mid-edit.
  const pickingTimer = (): boolean => ws.pickingTimerTaskId() === props.task.id
  let subtaskInputRef: HTMLInputElement | undefined
  let subtaskFormRef: HTMLFormElement | undefined
  let addToggleRef: HTMLButtonElement | undefined

  const isCompleted = (): boolean => props.task.completedDate === todayIso()
  const hasSubtasks = (): boolean => props.task.tasks.length > 0
  const visibleChildren = (): Task[] =>
    props.task.tasks.filter(isVisibleToday).slice().sort((a, b) => a.order - b.order)

  const activeTimerSet = (): TimerSet | null => {
    const sets = sortedSets(props.task.timerSets)
    if (sets.length === 0) return null
    return sets.find((s) => s.id === props.task.activeTimerSetId) ?? sets[0] ?? null
  }

  const isTimerActive = (): boolean => {
    const run = ws.timersRunner.runForTask(props.task.id)
    return run?.status === 'running' || run?.status === 'awaitingAdvance'
  }

  const childrenListKey = (): string =>
    subtasksListKey(props.groupId, props.task.id)

  const toggleAdding = (): void => {
    setAdding((v) => !v)
    if (!adding()) setNewSubtaskName('')
  }

  const submitSubtask = (event: Event): void => {
    event.preventDefault()
    const trimmed = newSubtaskName().trim()
    if (!trimmed) return
    void ws.tasks.addSubtask(props.groupId, props.task.id, trimmed)
    setNewSubtaskName('')
    subtaskInputRef?.focus()
  }

  const cancelAdding = (): void => {
    setAdding(false)
    setNewSubtaskName('')
  }

  onMount(() => {
    const onMouseDown = (event: MouseEvent): void => {
      if (!adding()) return
      const target = event.target
      if (!(target instanceof Node)) return
      if (subtaskFormRef && subtaskFormRef.contains(target)) return
      if (addToggleRef && addToggleRef.contains(target)) return
      cancelAdding()
    }
    const onKeyDown = (event: KeyboardEvent): void => {
      if (event.key === 'Escape' && adding()) cancelAdding()
    }
    document.addEventListener('mousedown', onMouseDown)
    document.addEventListener('keydown', onKeyDown)
    onCleanup(() => {
      document.removeEventListener('mousedown', onMouseDown)
      document.removeEventListener('keydown', onKeyDown)
    })
  })

  return (
    <Show when={isVisibleToday(props.task)}>
      <div
        ref={draggable.ref}
        // opacity-0 (not opacity-50): the floating ghost is shown by DragOverlay.
        class={cn('block group/task', draggable.isActiveDraggable && 'opacity-0')}
        data-testid={`task-item-${props.task.id}`}
      >
        <div
          class={cn(
            'flex items-center gap-2 py-2 px-3 rounded-md transition-colors',
            isCompleted() ? 'opacity-60' : 'hover:bg-foreground/5',
          )}
          onMouseEnter={() => setHovered(true)}
          onMouseLeave={() => setHovered(false)}
        >
          <span
            {...draggable.dragActivators}
            class={cn(
              'inline-flex cursor-grab active:cursor-grabbing text-subtle-foreground hover:text-foreground transition-opacity',
              hovered() ? 'opacity-100' : 'opacity-0',
            )}
            // Decorative — see GroupItem drag handle for rationale.
            aria-hidden="true"
          >
            <GripVertical size={16} />
          </span>

          <button
            type="button"
            onClick={() => void ws.tasks.toggleCompletion(props.groupId, props.task.id)}
            aria-pressed={isCompleted()}
            aria-label={
              isCompleted()
                ? `Mark ${props.task.name} incomplete`
                : `Mark ${props.task.name} complete`
            }
            class={cn(
              'tap-44 inline-flex h-7 w-7 shrink-0 items-center justify-center rounded-full border-2 border-border cursor-pointer transition-colors',
              isCompleted()
                ? 'bg-foreground'
                : 'bg-secondary-background hover:bg-foreground/10',
            )}
          >
            <Show when={isCompleted()}>
              <Check size={14} class="text-secondary-background" />
            </Show>
          </button>

          <Show when={hasSubtasks()}>
            <button
              type="button"
              class="tap-44 inline-flex h-7 w-7 items-center justify-center rounded-md text-foreground hover:bg-foreground/5 transition-colors cursor-pointer"
              onClick={() =>
                void ws.tasks.toggleOpen(props.groupId, props.task.id, !props.task.isOpen)
              }
              aria-expanded={props.task.isOpen}
              aria-label={props.task.isOpen ? 'Collapse subtasks' : 'Expand subtasks'}
            >
              <ChevronDown
                size={16}
                class={cn('transition-transform', !props.task.isOpen && '-rotate-90')}
              />
            </button>
          </Show>

          <span
            class={cn(
              'text-sm flex-1 font-semibold tracking-tight transition-all',
              isCompleted() && 'line-through text-subtle-foreground',
            )}
          >
            {props.task.name}
          </span>

          {/* Alarm badge — opens the picker when clicked. */}
          <Show when={props.task.alarm}>
            {(alarm) => (
              <button
                type="button"
                class="cursor-pointer"
                onClick={() => setPickingAlarm(true)}
                title={alarm().enabled === false ? 'Alarm off' : 'Change alarm'}
                aria-label={
                  alarm().enabled === false
                    ? `Enable alarm for ${props.task.name}`
                    : `Change alarm for ${props.task.name}`
                }
              >
                <AlarmBadge alarm={alarm()} />
              </button>
            )}
          </Show>

          {/* Timer badge — opens the editor when clicked. */}
          <Show when={activeTimerSet()}>
            {(timerSet) => (
              <button
                type="button"
                class="cursor-pointer"
                onClick={() => ws.openTimerPicker(props.task.id)}
                title="Edit timer"
                aria-label={`Edit timer for ${props.task.name}`}
              >
                <TimerBadge set={timerSet()} active={isTimerActive()} />
              </button>
            )}
          </Show>

          <div
            class={cn(
              'flex items-center gap-1.5 transition-opacity',
              hovered() ? 'opacity-100' : 'opacity-40',
            )}
          >
            <button
              ref={addToggleRef}
              type="button"
              onClick={toggleAdding}
              aria-expanded={adding()}
              title="Add subtask"
              aria-label="Add subtask"
              class="tap-44 inline-flex h-7 w-7 items-center justify-center rounded-md bg-secondary-background text-foreground border-2 border-border shadow-brutal-sm brutal-press cursor-pointer"
            >
              <Plus size={14} />
            </button>
            <Show when={!props.task.alarm}>
              <button
                type="button"
                onClick={() => setPickingAlarm(true)}
                title="Set alarm"
                aria-label={`Set alarm for ${props.task.name}`}
                class="tap-44 inline-flex h-7 w-7 items-center justify-center rounded-md bg-secondary-background text-foreground border-2 border-border shadow-brutal-sm brutal-press cursor-pointer"
              >
                <Bell size={14} />
              </button>
            </Show>
            <Show when={!activeTimerSet()}>
              <button
                type="button"
                onClick={() => ws.openTimerPicker(props.task.id)}
                title="Set timer"
                aria-label={`Set timer for ${props.task.name}`}
                class="tap-44 inline-flex h-7 w-7 items-center justify-center rounded-md bg-secondary-background text-foreground border-2 border-border shadow-brutal-sm brutal-press cursor-pointer"
              >
                <Timer size={14} />
              </button>
            </Show>
            <button
              type="button"
              onClick={() => void ws.tasks.delete(props.groupId, props.task.id)}
              title="Delete task"
              aria-label={`Delete ${props.task.name}`}
              class="tap-44 inline-flex h-7 w-7 items-center justify-center rounded-md bg-destructive text-destructive-foreground border-2 border-border shadow-brutal-sm brutal-press cursor-pointer"
            >
              <Trash2 size={14} />
            </button>
          </div>
        </div>

        <Show when={adding()}>
          <form
            ref={subtaskFormRef}
            onSubmit={submitSubtask}
            class="flex gap-2 mt-2 ml-10 mr-2 mb-2"
          >
            <input
              ref={(el) => {
                subtaskInputRef = el
                setTimeout(() => el?.focus(), 0)
              }}
              type="text"
              value={newSubtaskName()}
              onInput={(e) => setNewSubtaskName(e.currentTarget.value)}
              placeholder="Subtask name…"
              autocomplete="off"
              autocorrect="off"
              autocapitalize="off"
              spellcheck={false}
              aria-label="Subtask name"
              class="flex h-9 w-full flex-1 rounded-md border-2 border-border bg-secondary-background px-3 py-2 text-sm font-medium text-foreground placeholder:text-subtle-foreground shadow-brutal-sm focus-visible:shadow-brutal transition-shadow"
            />
            <button
              type="submit"
              class="inline-flex h-9 items-center justify-center gap-2 px-4 rounded-md bg-primary text-primary-foreground border-2 border-border shadow-brutal-sm brutal-press font-bold text-sm cursor-pointer disabled:opacity-50 disabled:pointer-events-none"
              disabled={!newSubtaskName().trim()}
            >
              Add
            </button>
          </form>
        </Show>

        <AlarmPicker
          show={pickingAlarm()}
          alarm={props.task.alarm}
          onAlarmChange={(next: AlarmSpec | null) =>
            void ws.tasks.setAlarm(props.groupId, props.task.id, next)
          }
          onClose={() => setPickingAlarm(false)}
        />

        <TimerEditor
          show={pickingTimer()}
          groupId={props.groupId}
          taskId={props.task.id}
          timerSets={props.task.timerSets}
          activeTimerSetId={props.task.activeTimerSetId}
          onTimerSetsChange={(next) =>
            void ws.tasks.updateTimerSets(props.groupId, props.task.id, next)
          }
          onActiveTimerSetIdChange={(id) =>
            void ws.tasks.setActiveTimerSetId(props.groupId, props.task.id, id)
          }
          onClose={() => ws.closeTimerPicker()}
        />

        <Show when={props.task.isOpen && visibleChildren().length > 0}>
          <div class="ml-7 mt-1 border-l border-subtle-foreground/40 pl-3">
            <Gap
              id={`gap:${childrenListKey()}:0`}
              listKey={childrenListKey() as ItemDragData['listKey']}
              insertAt={0}
              heightClass="h-2"
            />
            <For each={visibleChildren()}>{(child, i) => (
              <>
                <TaskItem task={child} groupId={props.groupId} parentId={props.task.id} />
                <Gap
                  id={`gap:${childrenListKey()}:${i() + 1}`}
                  listKey={childrenListKey() as ItemDragData['listKey']}
                  insertAt={i() + 1}
                  heightClass="h-2"
                />
              </>
            )}</For>
          </div>
        </Show>
      </div>
    </Show>
  )
}

// src/app/features/workspace/ui/task-item/task-item.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  ElementRef,
  TemplateRef,
  ViewContainerRef,
  computed,
  effect,
  inject,
  input,
  signal,
  viewChild,
} from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormsModule } from '@angular/forms';
import { CdkDrag, CdkDragDrop, CdkDragHandle, CdkDropList } from '@angular/cdk/drag-drop';
import {
  Overlay,
  OverlayModule,
  type ConnectedPosition,
  type OverlayRef,
} from '@angular/cdk/overlay';
import { TemplatePortal } from '@angular/cdk/portal';
import { LucideAngularModule } from 'lucide-angular';
import { AutofocusDirective } from '@shared/ui/autofocus/autofocus.directive';
import { ButtonDirective } from '@shared/ui/button/button.directive';
import { InputDirective } from '@shared/ui/input/input.directive';
import { cn } from '@shared/utils/cn';
import { todayIso } from '@shared/utils/dates';
import { AlarmBadgeComponent } from '@features/alarms/ui/alarm-badge/alarm-badge.component';
import { AlarmPickerComponent } from '@features/alarms/ui/alarm-picker/alarm-picker.component';
import type { AlarmSpec } from '@features/alarms/data-access/alarms.types';
import type { Task } from '@features/tasks/data-access/tasks.types';
import { isVisibleToday } from '@features/tasks/data-access/tasks.tree';
import { TimerEditorComponent } from '@features/timers/feature/timer-editor/timer-editor.component';
import { TimerBadgeComponent } from '@features/timers/ui/timer-badge/timer-badge.component';
import { sortedSets } from '@features/timers/data-access/timer-format';
import { TimersRunner } from '@features/timers/data-access/timers.runner';
import type { TimerSet } from '@features/timers/data-access/timers.types';
import { WorkspaceState } from '@features/workspace/data-access/workspace.state';

@Component({
  selector: 'app-task-item',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    FormsModule,
    CdkDrag,
    CdkDragHandle,
    CdkDropList,
    OverlayModule,
    LucideAngularModule,
    AutofocusDirective,
    ButtonDirective,
    InputDirective,
    AlarmBadgeComponent,
    AlarmPickerComponent,
    TimerEditorComponent,
    TimerBadgeComponent,
  ],
  templateUrl: './task-item.component.html',
  host: {
    class: 'block group/task',
  },
})
export class TaskItemComponent {
  private readonly state = inject(WorkspaceState);
  private readonly runner = inject(TimersRunner);
  private readonly overlay = inject(Overlay);
  private readonly viewContainerRef = inject(ViewContainerRef);
  private readonly destroyRef = inject(DestroyRef);

  readonly task = input.required<Task>();
  readonly groupId = input.required<string>();

  private readonly alarmTpl = viewChild.required<TemplateRef<unknown>>('alarmTpl');
  private readonly timerTpl = viewChild.required<TemplateRef<unknown>>('timerTpl');
  private readonly subtaskFormRef = viewChild<ElementRef<HTMLFormElement>>('subtaskForm');
  private readonly subtaskInputRef = viewChild<ElementRef<HTMLInputElement>>('subtaskInput');
  private readonly addToggleRef = viewChild<ElementRef<HTMLButtonElement>>('addToggle');

  protected readonly hovered = signal(false);
  protected readonly adding = signal(false);
  protected readonly newSubtaskName = signal('');
  protected readonly pickingAlarm = signal(false);
  protected readonly pickingTimer = signal(false);
  protected readonly pickingActions = signal(false);

  private alarmOverlayRef: OverlayRef | null = null;
  private timerOverlayRef: OverlayRef | null = null;

  protected readonly hasTimers = computed(() => this.task().timerSets.length > 0);

  protected readonly alarmMenuLabel = computed(() =>
    this.task().alarm ? 'Change alarm' : 'Set alarm',
  );

  protected readonly alarmMenuIcon = computed(() => (this.task().alarm ? 'bell-ring' : 'bell'));

  protected readonly timerMenuLabel = computed(() =>
    this.hasTimers() ? 'Edit timer' : 'Set timer',
  );

  protected readonly activeTimerSet = computed<TimerSet | null>(() => {
    const sets = sortedSets(this.task().timerSets);
    if (sets.length === 0) return null;
    const id = this.task().activeTimerSetId;
    return sets.find((s) => s.id === id) ?? sets[0];
  });

  protected readonly actionsMenuPositions: ConnectedPosition[] = [
    {
      originX: 'end',
      originY: 'bottom',
      overlayX: 'end',
      overlayY: 'top',
      offsetY: 6,
    },
    {
      originX: 'end',
      originY: 'top',
      overlayX: 'end',
      overlayY: 'bottom',
      offsetY: -6,
    },
    {
      originX: 'start',
      originY: 'bottom',
      overlayX: 'start',
      overlayY: 'top',
      offsetY: 6,
    },
  ];

  protected readonly visible = computed(() => isVisibleToday(this.task()));

  protected readonly isCompleted = computed(() => this.task().completedDate === todayIso());

  protected readonly isTimerActive = computed(() => {
    const r = this.runner.run();
    if (r.status !== 'running' && r.status !== 'awaitingAdvance') return false;
    return r.taskId === this.task().id;
  });

  protected readonly sortedChildren = computed(() =>
    this.task()
      .tasks.slice()
      .sort((a, b) => a.order - b.order),
  );

  protected readonly hasSubtasks = computed(() => this.task().tasks.length > 0);

  protected readonly rowClass = computed(() => {
    if (this.isTimerActive()) {
      return cn(
        'relative flex items-center gap-2 py-2 pl-5 pr-3 rounded-md bg-primary-soft transition-colors',
        "before:content-[''] before:absolute before:inset-y-0 before:left-0 before:w-1.5 before:bg-foreground before:rounded-l-md",
      );
    }
    return cn(
      'flex items-center gap-2 py-2 px-3 rounded-md transition-colors',
      this.isCompleted() ? 'opacity-60' : 'hover:bg-foreground/5',
    );
  });

  protected readonly dragHandleClass = computed(() =>
    cn(
      'cursor-grab active:cursor-grabbing text-subtle-foreground hover:text-foreground transition-opacity',
      this.hovered() || this.isTimerActive() ? 'opacity-100' : 'opacity-0',
    ),
  );

  protected readonly completionCircleClass = computed(() =>
    cn(
      'inline-flex h-7 w-7 shrink-0 items-center justify-center rounded-full border-2 border-border cursor-pointer transition-colors',
      this.isCompleted() ? 'bg-foreground' : 'bg-secondary-background hover:bg-foreground/10',
    ),
  );

  protected readonly nameClass = computed(() =>
    cn(
      'text-sm flex-1 font-semibold tracking-tight transition-all',
      this.isCompleted() && 'line-through text-subtle-foreground',
    ),
  );

  protected readonly actionsVisible = computed(
    () => this.hovered() || this.pickingActions() || this.pickingAlarm() || this.pickingTimer(),
  );

  protected readonly actionsClass = computed(() =>
    cn(
      'flex items-center gap-1.5 transition-opacity',
      this.actionsVisible() ? 'opacity-100' : 'opacity-40',
    ),
  );

  protected readonly chevronClass = computed(() =>
    cn('h-4 w-4 transition-transform duration-200', !this.task().isOpen && '-rotate-90'),
  );

  constructor() {
    this.destroyRef.onDestroy(() => {
      this.alarmOverlayRef?.dispose();
      this.timerOverlayRef?.dispose();
    });

    effect((onCleanup) => {
      if (!this.adding()) return;
      const onMouseDown = (event: MouseEvent) => {
        const target = event.target;
        if (!(target instanceof Node)) return;
        const form = this.subtaskFormRef()?.nativeElement;
        if (form && form.contains(target)) return;
        const toggle = this.addToggleRef()?.nativeElement;
        if (toggle && toggle.contains(target)) return;
        this.cancelAdding();
      };
      const onKeyDown = (event: KeyboardEvent) => {
        if (event.key === 'Escape') this.cancelAdding();
      };
      document.addEventListener('mousedown', onMouseDown);
      document.addEventListener('keydown', onKeyDown);
      onCleanup(() => {
        document.removeEventListener('mousedown', onMouseDown);
        document.removeEventListener('keydown', onKeyDown);
      });
    });
  }

  protected toggleOpen(): void {
    this.state.toggleTaskOpen(this.groupId(), this.task().id, !this.task().isOpen);
  }

  protected toggleCompletion(): void {
    this.state.toggleTaskCompletion(this.groupId(), this.task().id);
  }

  protected deleteTask(): void {
    this.state.deleteTask(this.groupId(), this.task().id);
  }

  protected toggleAdding(): void {
    this.adding.update((v) => !v);
    if (!this.adding()) this.newSubtaskName.set('');
  }

  protected submitSubtask(event: Event): void {
    event.preventDefault();
    const name = this.newSubtaskName().trim();
    if (!name) return;
    this.state.addSubtask(this.groupId(), this.task().id, name);
    this.newSubtaskName.set('');
    this.subtaskInputRef()?.nativeElement.focus();
  }

  protected cancelAdding(): void {
    this.adding.set(false);
    this.newSubtaskName.set('');
  }

  protected toggleAlarmPicker(): void {
    if (this.pickingAlarm()) {
      this.onAlarmPickerClose();
    } else {
      this.openAlarmPicker();
    }
  }

  protected onAlarmChange(alarm: AlarmSpec | null): void {
    this.state.setTaskAlarm(this.groupId(), this.task().id, alarm);
  }

  protected onAlarmPickerClose(): void {
    this.alarmOverlayRef?.dispose();
    this.alarmOverlayRef = null;
    this.pickingAlarm.set(false);
  }

  protected toggleTimerPicker(): void {
    if (this.pickingTimer()) {
      this.onTimerPickerClose();
    } else {
      this.openTimerPicker();
    }
  }

  protected onTimerSetsChange(sets: TimerSet[]): void {
    this.state.setTaskTimerSets(this.groupId(), this.task().id, sets);
  }

  protected onActiveTimerSetIdChange(id: string | null): void {
    this.state.setTaskActiveTimerSetId(this.groupId(), this.task().id, id);
  }

  protected onTimerPickerClose(): void {
    this.timerOverlayRef?.dispose();
    this.timerOverlayRef = null;
    this.pickingTimer.set(false);
  }

  protected toggleActions(): void {
    this.pickingActions.update((v) => !v);
  }

  protected onActionsClose(): void {
    this.pickingActions.set(false);
  }

  protected onActionsKeydown(event: KeyboardEvent): void {
    if (event.key === 'Escape') {
      event.stopPropagation();
      this.onActionsClose();
    }
  }

  protected openAlarmFromMenu(): void {
    this.pickingActions.set(false);
    this.openAlarmPicker();
  }

  protected openTimerFromMenu(): void {
    this.pickingActions.set(false);
    this.openTimerPicker();
  }

  protected onChildrenDrop(event: CdkDragDrop<Task[]>): void {
    if (event.previousIndex === event.currentIndex) return;
    this.state.reorderTasks(
      this.groupId(),
      this.task().id,
      event.previousIndex,
      event.currentIndex,
    );
  }

  private openAlarmPicker(): void {
    if (this.alarmOverlayRef) return;
    this.alarmOverlayRef = this.createCenteredOverlay();
    this.alarmOverlayRef.attach(new TemplatePortal(this.alarmTpl(), this.viewContainerRef));
    this.alarmOverlayRef
      .backdropClick()
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe(() => this.onAlarmPickerClose());
    this.alarmOverlayRef
      .keydownEvents()
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe((event) => {
        if (event.key === 'Escape') {
          event.stopPropagation();
          this.onAlarmPickerClose();
        }
      });
    this.pickingAlarm.set(true);
  }

  private openTimerPicker(): void {
    if (this.timerOverlayRef) return;
    this.timerOverlayRef = this.createCenteredOverlay();
    this.timerOverlayRef.attach(new TemplatePortal(this.timerTpl(), this.viewContainerRef));
    this.timerOverlayRef
      .backdropClick()
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe(() => this.onTimerPickerClose());
    this.timerOverlayRef
      .keydownEvents()
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe((event) => {
        if (event.key === 'Escape') {
          event.stopPropagation();
          this.onTimerPickerClose();
        }
      });
    this.pickingTimer.set(true);
  }

  private createCenteredOverlay(): OverlayRef {
    const positionStrategy = this.overlay
      .position()
      .global()
      .centerHorizontally()
      .centerVertically();
    return this.overlay.create({
      positionStrategy,
      hasBackdrop: true,
      backdropClass: 'cdk-overlay-dark-backdrop',
      scrollStrategy: this.overlay.scrollStrategies.block(),
    });
  }
}

@if (visible()) {
  <div [class]="rowClass()" (mouseenter)="hovered.set(true)" (mouseleave)="hovered.set(false)">
    <span cdkDragHandle [class]="dragHandleClass()" aria-label="Drag to reorder">
      <lucide-icon name="grip-vertical" class="h-4 w-4" />
    </span>

    <button
      type="button"
      (click)="toggleCompletion()"
      [attr.aria-pressed]="isCompleted()"
      [attr.aria-label]="
        isCompleted() ? 'Mark ' + task().name + ' incomplete' : 'Mark ' + task().name + ' complete'
      "
      [class]="completionCircleClass()"
    >
      @if (isCompleted()) {
        <lucide-icon name="check" class="h-3.5 w-3.5 text-secondary-background" />
      }
    </button>

    @if (hasSubtasks()) {
      <button
        appButton
        variant="ghost"
        size="icon-sm"
        btnClass="h-7 w-7"
        (click)="toggleOpen()"
        [attr.aria-expanded]="task().isOpen"
        [attr.aria-label]="task().isOpen ? 'Collapse subtasks' : 'Expand subtasks'"
        type="button"
      >
        <lucide-icon name="chevron-down" [class]="chevronClass()" />
      </button>
    }

    <span [class]="nameClass()">{{ task().name }}</span>

    @if (task().alarm; as alarm) {
      <button
        type="button"
        class="cursor-pointer"
        (click)="toggleAlarmPicker()"
        title="Change alarm"
      >
        <app-alarm-badge [alarm]="alarm" />
      </button>
    }

    @if (activeTimerSet(); as timerSet) {
      <button type="button" class="cursor-pointer" (click)="toggleTimerPicker()" title="Edit timer">
        <app-timer-badge [set]="timerSet" [active]="isTimerActive()" />
      </button>
    }

    <div [class]="actionsClass()">
      <button
        #addToggle
        appButton
        variant="neutral"
        size="icon-sm"
        (click)="toggleAdding()"
        [attr.aria-expanded]="adding()"
        title="Add subtask"
        aria-label="Add subtask"
        type="button"
      >
        <lucide-icon name="plus" class="h-4 w-4" />
      </button>
      <button
        appButton
        variant="destructive"
        size="icon-sm"
        (click)="deleteTask()"
        title="Delete task"
        aria-label="Delete task"
        type="button"
      >
        <lucide-icon name="trash-2" class="h-4 w-4" />
      </button>
      <button
        #menuTrigger="cdkOverlayOrigin"
        cdkOverlayOrigin
        appButton
        variant="neutral"
        size="icon-sm"
        (click)="toggleActions()"
        [attr.aria-expanded]="pickingActions()"
        aria-haspopup="menu"
        title="More actions"
        aria-label="More actions"
        type="button"
      >
        <lucide-icon name="more-vertical" class="h-4 w-4" />
      </button>
    </div>
  </div>

  <ng-template
    cdkConnectedOverlay
    [cdkConnectedOverlayOrigin]="menuTrigger"
    [cdkConnectedOverlayOpen]="pickingActions()"
    [cdkConnectedOverlayPositions]="actionsMenuPositions"
    [cdkConnectedOverlayHasBackdrop]="true"
    cdkConnectedOverlayBackdropClass="cdk-overlay-transparent-backdrop"
    (backdropClick)="onActionsClose()"
    (detach)="onActionsClose()"
    (overlayKeydown)="onActionsKeydown($event)"
  >
    <div
      class="min-w-44 rounded-md border-2 border-border bg-background shadow-brutal overflow-hidden py-1"
      role="menu"
    >
      <button
        type="button"
        role="menuitem"
        class="flex w-full items-center gap-2 px-3 py-2 text-left text-sm font-semibold tracking-tight hover:bg-secondary-background transition-colors cursor-pointer"
        (click)="openAlarmFromMenu()"
      >
        <lucide-icon [name]="alarmMenuIcon()" class="h-4 w-4 shrink-0" />
        <span>{{ alarmMenuLabel() }}</span>
      </button>
      <button
        type="button"
        role="menuitem"
        class="flex w-full items-center gap-2 px-3 py-2 text-left text-sm font-semibold tracking-tight hover:bg-secondary-background transition-colors cursor-pointer"
        (click)="openTimerFromMenu()"
      >
        <lucide-icon name="timer" class="h-4 w-4 shrink-0" />
        <span>{{ timerMenuLabel() }}</span>
      </button>
    </div>
  </ng-template>

  <ng-template #alarmTpl>
    <app-alarm-picker
      [alarm]="task().alarm"
      (alarmChange)="onAlarmChange($event)"
      (closed)="onAlarmPickerClose()"
    />
  </ng-template>

  <ng-template #timerTpl>
    <app-timer-editor
      [groupId]="groupId()"
      [taskId]="task().id"
      [timerSets]="task().timerSets"
      [activeTimerSetId]="task().activeTimerSetId"
      (timerSetsChange)="onTimerSetsChange($event)"
      (activeTimerSetIdChange)="onActiveTimerSetIdChange($event)"
      (closed)="onTimerPickerClose()"
    />
  </ng-template>

  @if (adding()) {
    <form #subtaskForm (submit)="submitSubtask($event)" class="flex gap-2 mt-2 ml-10 mr-2 mb-2">
      <input
        #subtaskInput
        appInput
        appAutofocus
        [ngModel]="newSubtaskName()"
        (ngModelChange)="newSubtaskName.set($event)"
        name="subtaskName"
        placeholder="Subtask name…"
        class="h-9 text-sm"
      />
      <button appButton size="sm" btnClass="h-9 px-4" type="submit">Add</button>
    </form>
  }

  @if (task().isOpen && hasSubtasks()) {
    <div class="ml-7 mt-1 border-l border-subtle-foreground/40 pl-3">
      <div cdkDropList (cdkDropListDropped)="onChildrenDrop($event)">
        @for (child of sortedChildren(); track child.id) {
          <div cdkDrag>
            <app-task-item [task]="child" [groupId]="groupId()" />
          </div>
        }
      </div>
    </div>
  }
}
